// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_contact from "./routes/api/contact.ts";
import * as $docs_index from "./routes/docs/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $terminos_y_condiciones_index from "./routes/terminos-y-condiciones/index.tsx";
import * as $NavBar from "./islands/NavBar.tsx";
import * as $Question from "./islands/Question.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/api/contact.ts": $api_contact,
    "./routes/docs/index.tsx": $docs_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/terminos-y-condiciones/index.tsx": $terminos_y_condiciones_index,
  },
  islands: {
    "./islands/NavBar.tsx": $NavBar,
    "./islands/Question.tsx": $Question,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
