// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/greet/[name].tsx";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/NavBar.tsx";
import * as $$1 from "./islands/OpenAPIExplorer.tsx";
import * as $$2 from "./islands/Question.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/greet/[name].tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/NavBar.tsx": $$0,
    "./islands/OpenAPIExplorer.tsx": $$1,
    "./islands/Question.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
